# Nome da aplicação
spring.application.name=Cotacao-de-viagem

# Configuração do Banco de Dados H2 (Em Memória)
spring.datasource.url=jdbc:h2:mem:cotacaodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Ativar o Painel do H2 no Navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configurações do Hibernate e JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
